/* Optional views load their data/maps only after the user opens them. */
(function(){
'use strict';
const M=window.TrappFeaturesModel,$=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const RAW='https://raw.githubusercontent.com/tacurry0/2025football_program/main/trapp/data/';
const VISITS='trapp_stadium_visits_v1';
const today=()=>new Intl.DateTimeFormat('sv-SE',{timeZone:'Asia/Tokyo'}).format(new Date());
let app,club='niigata',request=0,map,markers,stadiums=[],mapPromise,visits=[],editing=null,photo='',selectedPoint=null;
async function json(url){const r=await fetch(url,{signal:AbortSignal.timeout(12000),cache:'no-cache'});if(!r.ok)throw new Error('HTTP '+r.status);return r.json();}
async function data(file){try{return await json(RAW+file);}catch(_){return json('./data/'+file);}}
function status(text){$('#visit-status').textContent=text;}
function show(mode){app.navigate(mode);}
function statCard(team,games,sideGames){const s=M.stats(games),a=M.stats(sideGames);return `<section class="fx-team-card"><div class="fx-team-heading"><img src="${esc(app.emblem(team))}" alt="" width="44" height="44"><h2>${esc(team)}</h2></div><div class="fx-form">${games.slice(0,5).map(r=>`<span class="fx-result ${r.outcome}" title="${esc(r.date+' '+r.opponent+' '+r.gf+'−'+r.ga)}">${r.outcome}</span>`).join('')||'<span>記録なし</span>'}</div><p class="fx-caption">直近5試合・左が最新</p><div class="fx-statline"><b>${s.W}<small>勝</small></b><b>${s.D}<small>分</small></b><b>${s.L}<small>敗</small></b></div><dl class="fx-metrics"><div><dt>得点 / 失点</dt><dd>${s.gf} / ${s.ga}</dd></div><div><dt>1試合平均得点</dt><dd>${s.played?(s.gf/s.played).toFixed(2):'—'}</dd></div><div><dt>${sideGames.side==='home'?'ホーム':'アウェイ'}成績</dt><dd>${a.W}勝 ${a.D}分 ${a.L}敗</dd></div></dl><p class="fx-caption">${a.played}試合を集計</p></section>`;}
function gameList(games){return games.map(r=>`<li><time>${esc(r.date)}</time><span class="fx-result ${r.outcome}">${r.outcome}</span><span>${esc(r.opponent)}<small>${r.homeSide?'HOME':'AWAY'} · ${esc(r.competition||({j1:'J1',j2:'J2',j3:'J3',leaguecup:'ルヴァンカップ',emperor:'天皇杯'}[r.league])||'公式戦')}</small></span><b>${r.gf} − ${r.ga}</b></li>`).join('')||'<li>該当する公式記録がありません。</li>';}
async function renderAnalysis(){
 const token=++request,host=$('#fx-analysis-content');host.innerHTML='<p class="fx-empty" role="status">対戦データを読み込んでいます…</p>';
 try{
  const [payloads,history]=await Promise.all([Promise.all(['j1','j2','j3','leaguecup','emperor'].map(l=>data(l==='j1'?'insights/j1.json':`results/2026_2027/${l}.json`).catch(()=>null))),data(`insights/${club}.json`).catch(()=>null)]);
  if(token!==request)return;
  const rows=M.unique([...app.results(),...payloads.flatMap(p=>p?.data||[])]).filter(r=>r.date>='2026-08-01');
  const match=M.nextMatch(app.schedule(),rows,club,today());
  if(!match){host.innerHTML='<p class="fx-empty">次の試合はまだ登録されていません。</p>';return;}
  const comp=window.TrappLeague.context(match).competition;
  const scope=$('#fx-analysis-scope').value;
  const selected=scope==='league'?rows.filter(r=>['j1','j2','j3'].includes(r.competition_id||r.league)):rows;
  const name=M.names[club],home=app.isHome(match);
  const own=M.teamGames(selected,name,match.date),opp=M.teamGames(selected,match.opponent,match.date);
  const ownSide=M.teamGames(selected,name,match.date,home?'home':'away');ownSide.side=home?'home':'away';
  const oppSide=M.teamGames(selected,match.opponent,match.date,home?'away':'home');oppSide.side=home?'away':'home';
  const h2h=M.teamGames([...(history?.data||[]),...rows],name,match.date).filter(r=>M.same(r.opponent,match.opponent));
  const h=M.stats(h2h),dates=payloads.map(p=>p?.fetchedAt).filter(Boolean).sort();
  host.innerHTML=`<div class="fx-fixture" data-club="${club}"><span class="fx-eyebrow">NEXT MATCH · ${esc(match.matchweek||comp||'')}</span><h2>${esc(name)}<span>vs</span>${esc(match.opponent)}</h2><p>${esc(match.date)} ${esc(match.time||'時刻未定')} · ${home?'HOME':'AWAY'}</p><p>${esc(match.venue||'会場未定')}</p><button type="button" class="fx-button" id="fx-open-match">試合詳細 <span aria-hidden="true">↗</span></button></div><p class="fx-caption">2026/27 ${scope==='league'?'J1・J2・J3':'J1・J2・J3・ルヴァン・天皇杯'} ／ 対戦日より前の終了済み試合</p><div class="fx-comparison">${statCard(name,own.slice(0,5),ownSide)}${statCard(match.opponent,opp.slice(0,5),oppSide)}</div>${!opp.length?'<p class="fx-notice">対戦相手の対象データがありません。取得後に表示されます。</p>':''}<section class="fx-card"><h2>直近の試合</h2><h3>${esc(name)}</h3><ul class="fx-games">${gameList(own.slice(0,5))}</ul><h3>${esc(match.opponent)}</h3><ul class="fx-games">${gameList(opp.slice(0,5))}</ul></section><section class="fx-card"><span class="fx-eyebrow">HEAD TO HEAD</span><h2>過去の対戦</h2><div class="fx-statline"><b>${h.W}<small>勝</small></b><b>${h.D}<small>分</small></b><b>${h.L}<small>敗</small></b></div><p class="fx-caption">${esc(name)}から見た収録済み${h.played}試合${h2h.length?' · '+esc(h2h.at(-1).date)+'〜'+esc(h2h[0].date):''}。PK戦は引き分けとして集計。</p><ul class="fx-games">${gameList(h2h.slice(0,10))}</ul>${!history?'<p class="fx-notice">過去の対戦記録を取得できません。現在のシーズンのみ表示しています。</p>':''}</section><p class="fx-caption">公式記録の確認: ${dates.length?esc(new Date(dates[0]).toLocaleString('ja-JP')):'日時不明'} · <a href="https://www.jleague.jp/" target="_blank" rel="noopener">J.LEAGUE</a></p>${payloads.some(p=>!p)?'<button class="fx-button" id="fx-retry">一部のデータを再取得</button>':''}`;
  $('#fx-open-match').onclick=()=>app.openMatch(match);if($('#fx-retry'))$('#fx-retry').onclick=renderAnalysis;
 }catch(e){if(token===request)host.innerHTML='<p class="fx-empty">データを読み込めませんでした。</p><button class="fx-button" id="fx-retry">再読み込み</button>';if($('#fx-retry'))$('#fx-retry').onclick=renderAnalysis;}
}
function readVisits(){try{const v=JSON.parse(localStorage.getItem(VISITS)||'[]');if(!Array.isArray(v)||!v.every(M.validVisit))throw Error();visits=v;}catch(_){visits=[];status('訪問記録を読み込めません。データ管理からバックアップを確認してください。');}}
function persist(next){localStorage.setItem(VISITS,JSON.stringify(next));visits=next;}
function venuePoint(name){const saved=visits.find(v=>M.norm(v.venue)===M.norm(name)&&v.lat!==null);return saved||stadiums.find(s=>M.norm(s.name)===M.norm(name)||(s.aliases||[]).some(a=>M.norm(a)===M.norm(name)));}
function loadMap(){if(mapPromise)return mapPromise;mapPromise=new Promise((resolve,reject)=>{if(window.L)return resolve();const css=document.createElement('link');css.rel='stylesheet';css.href='./vendor/leaflet/leaflet.css';document.head.append(css);const script=document.createElement('script');script.src='./vendor/leaflet/leaflet.js';script.onload=resolve;script.onerror=reject;document.head.append(script);}).then(()=>{
 map=L.map('stadium-map-canvas',{scrollWheelZoom:false}).setView([36.1,137.2],5);L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'}).addTo(map).on('tileerror',()=>{$('#map-network-status').textContent='地図を取得できません。訪問リストは引き続き利用できます。';});markers=L.layerGroup().addTo(map);map.on('click',e=>{if(!$('#visit-form').hidden){selectedPoint={lat:+e.latlng.lat.toFixed(6),lng:+e.latlng.lng.toFixed(6)};$('#visit-lat').value=selectedPoint.lat;$('#visit-lng').value=selectedPoint.lng;drawMarkers();}});drawMarkers();}).catch(()=>{mapPromise=null;$('#map-network-status').textContent='地図を読み込めません。訪問記録は下のフォームから保存できます。';});return mapPromise;}
function drawMarkers(){if(!map)return;markers.clearLayers();const groups=new Map();for(const v of visits){if(v.lat===null||$('#visit-club-filter').value!=='all'&&v.club!==$('#visit-club-filter').value)continue;const key=M.norm(v.venue);if(!groups.has(key))groups.set(key,[]);groups.get(key).push(v);}for(const group of groups.values()){const v=group[0],node=document.createElement('div');node.className='fx-map-popup';const b=document.createElement('b');b.textContent=v.venue;node.append(b,document.createElement('br'),document.createTextNode(group.length+'回訪問'));L.circleMarker([v.lat,v.lng],{radius:9,color:'#fff',weight:3,fillColor:v.club==='kumamoto'?'#b82030':'#e56b18',fillOpacity:1}).addTo(markers).bindPopup(node);}
 for(const s of stadiums){if(groups.has(M.norm(s.name)))continue;L.circleMarker([s.lat,s.lng],{radius:5,color:'#758395',weight:1,fillOpacity:.3}).addTo(markers).bindTooltip(s.name);}
 if(selectedPoint)L.circleMarker([selectedPoint.lat,selectedPoint.lng],{radius:11,color:'#135ed6',weight:3,fillOpacity:.2}).addTo(markers);
}
function renderVisits(){
 const filter=$('#visit-club-filter').value,rows=visits.filter(v=>filter==='all'||v.club===filter).sort((a,b)=>b.date.localeCompare(a.date));
 $('#visit-count').textContent=new Set(rows.map(v=>M.norm(v.venue))).size;$('#visit-total').textContent=rows.length;
 $('#visit-list').innerHTML=rows.map(v=>`<article class="fx-visit"><div class="fx-visit-meta"><time>${esc(v.date)}</time><span>${v.club==='niigata'?'新潟':v.club==='kumamoto'?'熊本':'その他'}</span></div><h3>${esc(v.venue)}</h3>${v.seat?`<p class="fx-caption">${esc(v.seat)}</p>`:''}${v.photo?`<img class="fx-visit-photo" src="${v.photo}" alt="${esc(v.venue)}の観戦写真" loading="lazy">`:''}${v.note?`<p class="fx-visit-note">${esc(v.note)}</p>`:''}<div class="fx-row"><button class="fx-button" data-edit-visit="${esc(v.id)}">編集</button>${v.lat!==null?`<button class="fx-button" data-map-visit="${esc(v.id)}">地図で見る</button>`:'<span class="fx-caption">位置未登録</span>'}</div></article>`).join('')||'<div class="fx-empty"><b>最初のスタジアムを記録しよう</b><p>訪れた日、座席、写真や思い出を残せます。</p></div>';
 const plans=app.schedule().filter(m=>localStorage.getItem('attend_'+window.TrappLeague.storageId(m))==='true'&&!visits.some(v=>v.matchKey===window.TrappLeague.storageId(m))).sort((a,b)=>b.date.localeCompare(a.date));
 $('#visit-plans').innerHTML=plans.slice(0,30).map(m=>`<button class="fx-plan" data-plan-key="${esc(window.TrappLeague.storageId(m))}"><span><time>${esc(m.date)}</time><b>${esc(m.venue||'会場未定')}</b><small>${m.club==='niigata'?'新潟':'熊本'} vs ${esc(m.opponent)}</small></span><span>${m.date<=today()?'記録する':'予定'} <span aria-hidden="true">↗</span></span></button>`).join('')||'<p class="fx-caption">試合詳細でチェックした観戦予定がここに表示されます。</p>';
 drawMarkers();
}
function editVisit(v={},match){
 editing=v.id||null;photo=v.photo||'';selectedPoint=v.lat!==undefined&&v.lat!==null?{lat:v.lat,lng:v.lng}:null;
 const f=$('#visit-form');f.reset();f.hidden=false;f.dataset.matchKey=v.matchKey||(match?window.TrappLeague.storageId(match):'');$('#visit-venue').value=v.venue||match?.venue||'';$('#visit-date').value=v.date||match?.date||today();$('#visit-date').max=today();$('#visit-club').value=v.club||match?.club||'niigata';$('#visit-seat').value=v.seat||'';$('#visit-note').value=v.note||'';$('#visit-delete').hidden=!editing;$('#visit-photo-preview').hidden=!photo;$('#visit-photo-preview').src=photo;$('#visit-photo-remove').hidden=!photo;
 const p=selectedPoint||venuePoint($('#visit-venue').value);$('#visit-lat').value=p?.lat??'';$('#visit-lng').value=p?.lng??'';if(p&&map)map.setView([p.lat,p.lng],14);status('');f.scrollIntoView({behavior:'auto',block:'start'});$('#visit-venue').focus({preventScroll:true});
}
async function openMap(){readVisits();try{stadiums=await json('./data/stadiums.json');}catch(_){stadiums=[];}const venues=[...new Set([...stadiums.map(s=>s.name),...app.schedule().map(m=>m.venue).filter(Boolean),...visits.map(v=>v.venue)])].sort((a,b)=>a.localeCompare(b,'ja'));$('#visit-venues').innerHTML=venues.map(v=>`<option value="${esc(v)}"></option>`).join('');renderVisits();await loadMap();if(map){map.invalidateSize();if(visits.some(v=>v.lat!==null))map.fitBounds(visits.filter(v=>v.lat!==null).map(v=>[v.lat,v.lng]),{padding:[35,35],maxZoom:13});}}
async function compress(file){if(file.size>20*1024*1024)throw Error('20MB以下の写真を選んでください。');if(!file.type.startsWith('image/'))throw Error('画像ファイルを選んでください。');const bitmap=await createImageBitmap(file),ratio=Math.min(1,1000/Math.max(bitmap.width,bitmap.height)),canvas=document.createElement('canvas');canvas.width=Math.round(bitmap.width*ratio);canvas.height=Math.round(bitmap.height*ratio);canvas.getContext('2d').drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close();let quality=.78,result;do{result=canvas.toDataURL('image/jpeg',quality);quality-=.12;}while(result.length>380000&&quality>.15);if(result.length>400000)throw Error('写真が大きいため、別の写真を選んでください。');return result;}
function bind(api){app=api;
 document.addEventListener('click',e=>{const b=e.target.closest('[data-feature]');if(b){e.preventDefault();e.stopPropagation();club=b.dataset.club||club;show(b.dataset.feature);}});
 $('#fx-analysis-club').onchange=e=>{club=e.target.value;renderAnalysis();};$('#fx-analysis-scope').onchange=renderAnalysis;
 $('#visit-add').onclick=()=>editVisit();$('#visit-cancel').onclick=()=>{$('#visit-form').hidden=true;selectedPoint=null;drawMarkers();};$('#visit-club-filter').onchange=renderVisits;
 $('#visit-venue').onchange=()=>{const p=venuePoint($('#visit-venue').value);$('#visit-lat').value=p?.lat??'';$('#visit-lng').value=p?.lng??'';selectedPoint=p?{lat:p.lat,lng:p.lng}:null;if(p&&map)map.setView([p.lat,p.lng],14);drawMarkers();};
 $('#visit-position').onclick=()=>{$('#stadium-map-canvas').scrollIntoView({behavior:'auto',block:'center'});$('#map-network-status').textContent='地図を拡大して、スタジアムの位置をタップしてください。';};
 let photoTask=Promise.resolve();$('#visit-photo').onchange=e=>{const file=e.target.files[0];if(!file)return;$('#visit-save').disabled=true;photoTask=compress(file).then(value=>{photo=value;$('#visit-photo-preview').src=photo;$('#visit-photo-preview').hidden=false;$('#visit-photo-remove').hidden=false;}).catch(e=>status(e.message)).finally(()=>{$('#visit-save').disabled=false;});};
 $('#visit-photo-remove').onclick=()=>{photo='';$('#visit-photo').value='';$('#visit-photo-preview').hidden=true;$('#visit-photo-remove').hidden=true;};
 $('#visit-form').onsubmit=async e=>{e.preventDefault();await photoTask;const lat=$('#visit-lat').value,lng=$('#visit-lng').value;const v={id:editing||crypto.randomUUID(),venue:$('#visit-venue').value.trim(),date:$('#visit-date').value,club:$('#visit-club').value,seat:$('#visit-seat').value.trim(),note:$('#visit-note').value.trim(),photo,lat:lat===''?null:Number(lat),lng:lng===''?null:Number(lng),matchKey:$('#visit-form').dataset.matchKey||''};if(!M.validVisit(v)||v.date>today()){status('日付・スタジアム名・位置を確認してください。訪問日は今日以前の日付を指定できます。');return;}try{persist([...visits.filter(r=>r.id!==v.id),v]);$('#visit-form').hidden=true;selectedPoint=null;renderVisits();status('訪問を保存しました。');$('#visit-status').scrollIntoView({behavior:'auto',block:'center'});}catch(_){status('保存容量が足りません。写真を外すか、バックアップ後に古い記録を整理してください。');}};
 $('#visit-delete').onclick=()=>{if(!editing||!confirm('この訪問記録を削除しますか？'))return;try{persist(visits.filter(v=>v.id!==editing));$('#visit-form').hidden=true;selectedPoint=null;renderVisits();status('訪問記録を削除しました。');}catch(_){status('削除できませんでした。');}};
 $('#visit-list').onclick=e=>{const edit=e.target.closest('[data-edit-visit]'),loc=e.target.closest('[data-map-visit]');if(edit)editVisit(visits.find(v=>v.id===edit.dataset.editVisit));if(loc){const v=visits.find(v=>v.id===loc.dataset.mapVisit);if(map)map.setView([v.lat,v.lng],15);$('#stadium-map-canvas').scrollIntoView({behavior:'auto',block:'center'});}};
 $('#visit-plans').onclick=e=>{const b=e.target.closest('[data-plan-key]');if(!b)return;const m=app.schedule().find(m=>window.TrappLeague.storageId(m)===b.dataset.planKey);if(m.date>today())app.openMatch(m);else editVisit({},m);};
 window.addEventListener('storage',e=>{if(e.key===VISITS&&document.body.dataset.mode==='stadium-map'){readVisits();renderVisits();}});
}
window.TrappFeatures={bind,openForClub(value){club=value;show("match-analysis");},open(mode){if(mode==='match-analysis'){$('#fx-analysis-club').value=club;renderAnalysis();}if(mode==='stadium-map')openMap();},validateVisits(raw){try{const v=JSON.parse(raw);return Array.isArray(v)&&v.every(M.validVisit)&&new Set(v.map(x=>x.id)).size===v.length;}catch(_){return false;}}};
})();
